server:
  port: 80

ssh:
  remote_jump_host: ec2-3-38-49-22.ap-northeast-2.compute.amazonaws.com
  ssh_port: 22
  user: ubuntu
  private_key : C:/Users/5600X-2060/.ssh/cinetalk-server-passkey.pem
  database_port: 3306

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cr06wigqodqc.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: admin
    password: qwer1234!

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ZlS_SJtn3r3v8GzuvoEN
            client-secret: 5Na6cINIVr
            redirect-uri: https://server.cinetalk.site/login/oauth2/code/naver
            #redirect-uri: http://localhost:80/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image,mobile
          google:
            client-name: google
            client-id: 990375759582-uauvot1i5dcq368ir6018c23c2mlf47s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://server.cinetalk.site/login/oauth2/code/google
            #redirect-uri: http://localhost:80/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email,https://www.googleapis.com/auth/user.birthday.read,https://www.googleapis.com/auth/user.gender.read
          kakao:
            client-name: kakao
            client-id: dddf0b88ada935e84093e84df995be33
            client-secret: a8KAE9PqewRLeTwvXhMCliyFaxPTbMuX
            redirect-uri: https://server.cinetalk.site/login/oauth2/code/kakao
            #redirect-uri: http://localhost:80/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            #scope: account_email,profile_nickname,profile_image,name,gender,birthday,birthyear
            scope: account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: 3.38.49.22
      port: 6379
      password: qwer1234!
