server:
  port: 80

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cb4g20es8n6f.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ZlS_SJtn3r3v8GzuvoEN
            client-secret: 5Na6cINIVr
            redirect-uri: http://localhost:8089/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image,mobile
          google:
            client-name: google
            client-id: 990375759582-uauvot1i5dcq368ir6018c23c2mlf47s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8089/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email,https://www.googleapis.com/auth/user.birthday.read,https://www.googleapis.com/auth/user.gender.read
          kakao:
            client-name: kakao
            client-id: 800cc786d3549b13be4c7ecc5c5c0ee2
            client-secret: ppMlYGDVqn9H7BYtltWW5uJWnEvvnGY5
            redirect-uri: http://localhost:8089/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email,profile_nickname,profile_image,name,gender,birthday,birthyear

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
