server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/cicdtalk?characterEncoding=UTF-8&severTimezone=Asia/Seoul
    username: cinetalk
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: mysql
    database - platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ZlS_SJtn3r3v8GzuvoEN
            client-secret: 5Na6cINIVr
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image,mobile
          google:
            client-name: google
            client-id: 990375759582-uauvot1i5dcq368ir6018c23c2mlf47s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          kakao:
            client-name: kakao
            client-id: dddf0b88ada935e84093e84df995be33
            client-secret: a8KAE9PqewRLeTwvXhMCliyFaxPTbMuX
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email,profile_nickname,profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id