server:
  port: 8089

spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URI}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #이거 안해주니깐 미친놈이 Find 테이블을 find 로 바꿔버림
        dialect: org.hibernate.dialect.MariaDBDialect
        show-sql: true
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: ${NAVER_CLIENT_AUTHORIZATION_GRANT_TYPE}
            scope: ${NAVER_SCOPE}
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope: ${GOOGLE_SCOPE}
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SERCRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            scope: ${KAKAO_SCOPE}

        provider:
          naver:
            authorization-uri: ${PROVIDER_NAVER_AUTHORIZATION_URI}
            token-uri: ${PROVIDER_NAVER_TOKEN_URI}
            user-info-uri: ${PROVIDER_NAVER_USER_INFO_URI}
            user-name-attribute: ${PROVIDER_NAVER_USER_NAME_ATTRIBUTE}
          kakao:
            authorization-uri: ${PROVIDER_KAKAO_AUTHORIZATION_URI}
            token-uri: ${PROVIDER_KAKAO_TOKEN_URI}
            user-info-uri: ${PROVIDER_KAKAO_USER_INFO_URI}
            user-name-attribute: ${PROVIDER_KAKAO_USER_NAME_ATTRIBUTE}

---
spring:
  config:
    activate:
      on-profile: common

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cinetalk-back-database:3306/cinetalk-back
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: cinetalk-back-redis
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      show-sql: true
      format_sql: true

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: ${NAVER_CLIENT_AUTHORIZATION_GRANT_TYPE}
            scope: ${NAVER_SCOPE}
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope: ${GOOGLE_SCOPE}
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SERCRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            scope: ${KAKAO_SCOPE}

        provider:
          naver:
            authorization-uri: ${PROVIDER_NAVER_AUTHORIZATION_URI}
            token-uri: ${PROVIDER_NAVER_TOKEN_URI}
            user-info-uri: ${PROVIDER_NAVER_USER_INFO_URI}
            user-name-attribute: ${PROVIDER_NAVER_USER_NAME_ATTRIBUTE}
          kakao:
            authorization-uri: ${PROVIDER_KAKAO_AUTHORIZATION_URI}
            token-uri: ${PROVIDER_KAKAO_TOKEN_URI}
            user-info-uri: ${PROVIDER_KAKAO_USER_INFO_URI}
            user-name-attribute: ${PROVIDER_KAKAO_USER_NAME_ATTRIBUTE}

cinetalk:
  back:
    base:
      url: http://3.37.21.244/dir/