name: cinetalk-pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-java-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Docker login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: |
          docker build -t app .

      - name: Docker tag
        run: |
          docker tag app kto5294/cinetalk:latest

      - name: Docker push
        run: |
          docker push kto5294/cinetalk:latest 

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker pull kto5294/cinetalk:latest
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps --filter 'status=exited' -a -q) || true
            docker run -d -p 80:80 kto5294/cinetalk:latest
            docker image prune -a -f