# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: kallis0926
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and release to DockerHub
        env:
          NAME: kallis0926
          APP: cinetalk-back
        run: |
          docker build -t kallis0926/cinetalk-back -f ./Dockerfile . # 여기서 DockerFile 로 썼다가 에러남..
          docker push kallis0926/cinetalk-back

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master

        with:
          username: ec2-user
          host: 3.37.21.244
          key: ${{ secrets.AWS_PEM_KEY }}

          script: |
            cd cinetalk-back
            docker-compose down --rmi all
            docker pull kallis0926/cinetalk-back
            docker-compose up -d --build