name: ci-cd-pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  run-java-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew clean build -x test

  build-image:
    needs: run-java-gradle
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  cd-pipeline:
    needs: build-image
    name: continuous deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          username: ec2-user
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.AWS_PEM_KEY }}
          port: 22
          script: cd /home/ec2-user/cinetalk-back && docker-compose -f docker-compose.yml up -d --build