# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: kallis0926
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and release to DockerHub
        env:
          NAME: kallis0926
          APP: cinetalk-back
        run: |
          docker build -t kallis0926/cinetalk-back -f ./Dockerfile .
          docker push kallis0926/cinetalk-back

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.AWS_PEM_KEY }}

#      - name: deploy
#        run: |
#          chmod +x ./deploy.sh
#          ./deploy.sh

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master

        with:
          username: ec2-user
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.AWS_PEM_KEY }}
          port: 22

          script: |
            cd cinetalk-back
            docker-compose -f docker-compose.yml down --rmi all
            docker pull kallis0926/cinetalk-back
            docker-compose -f docker-compose.yml up -d --build
